// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PartmanTenant struct {
	ID            string
	ParentTableID string
	CreatedAt     pgtype.Timestamptz
}
