// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const getTenants = `-- name: GetTenants :many
SELECT t.id as tenant_id, pt.id as parent_table_id
FROM partman.tenants t
         JOIN partman.parent_tables pt ON pt.id = t.parent_table_id
WHERE pt.table_name = $1
  AND pt.schema_name = $2
ORDER BY t.id
`

type GetTenantsParams struct {
	TableName  string
	SchemaName string
}

type GetTenantsRow struct {
	TenantID      string
	ParentTableID string
}

func (q *Queries) GetTenants(ctx context.Context, arg GetTenantsParams) ([]GetTenantsRow, error) {
	rows, err := q.db.Query(ctx, getTenants, arg.TableName, arg.SchemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantsRow
	for rows.Next() {
		var i GetTenantsRow
		if err := rows.Scan(&i.TenantID, &i.ParentTableID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
