// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE
FROM partman.tenants
WHERE parent_table_id = $1
  AND id = $2
`

type DeleteTenantParams struct {
	ParentTableID string
	ID            string
}

func (q *Queries) DeleteTenant(ctx context.Context, arg DeleteTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenant, arg.ParentTableID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTenants = `-- name: GetTenants :many
SELECT t.id as tenant_id, pt.id as parent_table_id
FROM partman.tenants t
         JOIN partman.parent_tables pt ON pt.id = t.parent_table_id
WHERE pt.table_name = $1
  AND pt.schema_name = $2
ORDER BY t.id
`

type GetTenantsParams struct {
	TableName  string
	SchemaName string
}

type GetTenantsRow struct {
	TenantID      string
	ParentTableID string
}

func (q *Queries) GetTenants(ctx context.Context, arg GetTenantsParams) ([]GetTenantsRow, error) {
	rows, err := q.db.Query(ctx, getTenants, arg.TableName, arg.SchemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantsRow
	for rows.Next() {
		var i GetTenantsRow
		if err := rows.Scan(&i.TenantID, &i.ParentTableID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForParent = `-- name: ListTenantsForParent :many
SELECT id, parent_table_id, created_at
FROM partman.tenants
WHERE parent_table_id = $1
ORDER BY id
`

func (q *Queries) ListTenantsForParent(ctx context.Context, parentTableID string) ([]PartmanTenant, error) {
	rows, err := q.db.Query(ctx, listTenantsForParent, parentTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartmanTenant
	for rows.Next() {
		var i PartmanTenant
		if err := rows.Scan(&i.ID, &i.ParentTableID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenant = `-- name: UpsertTenant :execrows
INSERT INTO partman.tenants (id, parent_table_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertTenantParams struct {
	ID            string
	ParentTableID string
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertTenant, arg.ID, arg.ParentTableID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
