// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetTenants(ctx context.Context, arg GetTenantsParams) ([]GetTenantsRow, error)
}

var _ Querier = (*Queries)(nil)
