// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	DeleteTenant(ctx context.Context, arg DeleteTenantParams) (int64, error)
	GetTenants(ctx context.Context, arg GetTenantsParams) ([]GetTenantsRow, error)
	ListTenantsForParent(ctx context.Context, parentTableID string) ([]PartmanTenant, error)
	UpsertTenant(ctx context.Context, arg UpsertTenantParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
