# 💡 TIP
#
# If you want to override anything in this file, create an adjacent file called
# `mise.local.toml`. That file is not checked in to the repository. Using this
# file, you can specify more tools or different versions of the listed ones below as
# well as overriding environment variables.
[tools]
go = "1.25.4"
golangci-lint = "2.4.0"

"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/daixiang0/gci" = "latest"

[env]
DATABASE_URL = "postgres://rtukpe:postgres@localhost:5432/pg_part?sslmode=disable"