// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	UpsertPartition(ctx context.Context, arg UpsertPartitionParams) error
}

var _ Querier = (*Queries)(nil)
