// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPartition = `-- name: UpsertPartition :exec
INSERT INTO partman.partitions
(id,
 name,
 parent_table_id,
 tenant_id,
 partition_by,
 partition_type,
 partition_bounds_from,
 partition_bounds_to)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8)
ON CONFLICT DO NOTHING
RETURNING id, name, parent_table_id, tenant_id, partition_by, partition_type, partition_bounds_from, partition_bounds_to, created_at, updated_at
`

type UpsertPartitionParams struct {
	ID                  string
	Name                string
	ParentTableID       string
	TenantID            pgtype.Text
	PartitionBy         string
	PartitionType       string
	PartitionBoundsFrom pgtype.Timestamptz
	PartitionBoundsTo   pgtype.Timestamptz
}

func (q *Queries) UpsertPartition(ctx context.Context, arg UpsertPartitionParams) error {
	_, err := q.db.Exec(ctx, upsertPartition,
		arg.ID,
		arg.Name,
		arg.ParentTableID,
		arg.TenantID,
		arg.PartitionBy,
		arg.PartitionType,
		arg.PartitionBoundsFrom,
		arg.PartitionBoundsTo,
	)
	return err
}
