// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	FindActivePartitionByBounds(ctx context.Context, arg FindActivePartitionByBoundsParams) (PartmanPartition, error)
	GetDefaultPartition(ctx context.Context, arg GetDefaultPartitionParams) (PartmanPartition, error)
	ListExpiredPartitions(ctx context.Context, arg ListExpiredPartitionsParams) ([]PartmanPartition, error)
	ListPartitionsForParent(ctx context.Context, parentTableID string) ([]PartmanPartition, error)
	MarkPartitionDetached(ctx context.Context, id string) error
	MarkPartitionDropped(ctx context.Context, id string) error
	UpsertPartition(ctx context.Context, arg UpsertPartitionParams) error
}

var _ Querier = (*Queries)(nil)
