// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PartmanParentTable struct {
	ID                   string
	SchemaName           string
	TableName            string
	TenantColumn         pgtype.Text
	PartitionBy          string
	PartitionType        string
	PartitionInterval    string
	RetentionPeriod      pgtype.Interval
	RetentionKeepTable   bool
	RetentionSchema      pgtype.Text
	AutomaticMaintenance bool
	Premake              int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}
