// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	UpsertParentTable(ctx context.Context, arg UpsertParentTableParams) (PartmanParentTable, error)
}

var _ Querier = (*Queries)(nil)
