// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetParentTable(ctx context.Context, arg GetParentTableParams) (PartmanParentTable, error)
	ListParentTables(ctx context.Context) ([]PartmanParentTable, error)
	UpdateAutomaticMaintenance(ctx context.Context, arg UpdateAutomaticMaintenanceParams) error
	UpsertParentTable(ctx context.Context, arg UpsertParentTableParams) (PartmanParentTable, error)
}

var _ Querier = (*Queries)(nil)
