// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertParentTable = `-- name: UpsertParentTable :one
INSERT INTO partman.parent_tables
(id, table_name, schema_name,
 tenant_column, partition_by,
 partition_type, partition_interval,
 partition_count, retention_period)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9)
ON CONFLICT DO NOTHING
RETURNING id, schema_name, table_name, tenant_column, partition_by, partition_type, partition_interval, partition_count, retention_period, created_at, updated_at
`

type UpsertParentTableParams struct {
	ID                string
	TableName         string
	SchemaName        string
	TenantColumn      pgtype.Text
	PartitionBy       string
	PartitionType     string
	PartitionInterval string
	PartitionCount    int32
	RetentionPeriod   string
}

func (q *Queries) UpsertParentTable(ctx context.Context, arg UpsertParentTableParams) (PartmanParentTable, error) {
	row := q.db.QueryRow(ctx, upsertParentTable,
		arg.ID,
		arg.TableName,
		arg.SchemaName,
		arg.TenantColumn,
		arg.PartitionBy,
		arg.PartitionType,
		arg.PartitionInterval,
		arg.PartitionCount,
		arg.RetentionPeriod,
	)
	var i PartmanParentTable
	err := row.Scan(
		&i.ID,
		&i.SchemaName,
		&i.TableName,
		&i.TenantColumn,
		&i.PartitionBy,
		&i.PartitionType,
		&i.PartitionInterval,
		&i.PartitionCount,
		&i.RetentionPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
